AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role for GitHub Actions

Parameters:
  OIDCProviderArn:
    Type: String
  GitHubUser:
    Type: String
  GitHubRepo:
    Type: String
  S3Bucket:
    Type: String
  S3KeyPrefix:
    Type: String
    Default: ""
  CloudFrontDistributionId:
    Type: String

Resources:
  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubUser}/${GitHubRepo}:environment:Deploy"
      Policies:
        - PolicyName: Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}/${S3KeyPrefix}*"
              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource:
                  - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistributionId}"

Outputs:
  RoleArn:
    Value: !GetAtt DeployRole.Arn
